# Lifecycle: created=2026-04-28; last_reviewed=2026-04-28; last_reused=2026-04-28
# Purpose: Prove architecture/topology.yaml digest_profiles and the generated Python mirror cannot silently drift.
# Reuse: Run whenever digest_profiles or scripts/digest_profiles_export.py changes.
# Created: 2026-04-28
# Last reused/audited: 2026-04-28
# Authority basis: round2_verdict.md §2.1 D1 + Tier 2 Phase 3 ITEM #14-followup
# dispatch (digest_profiles → Python migration scaffolding). Per Fitz "test
# relationships, not just functions" — this is a CROSS-MODULE relationship test
# that asserts the YAML and Python representations of digest_profiles are
# byte-for-byte equivalent (so neither can drift without the other failing CI).
"""Equivalence tests for digest_profiles YAML <-> Python mirror.

Phase 3 status: YAML is canonical truth source; architecture/digest_profiles.py
is a derived mirror generated by scripts/digest_profiles_export.py. These
relationship tests assert the mirror is in sync — failing them means either:

  (a) Someone edited the YAML without re-running the exporter.
  (b) Someone edited the .py directly (forbidden; auto-generated header warns).
  (c) The exporter has a bug.

Phase 3.5+ may flip the truth source to Python; until then, these tests are
the antibody preventing silent drift between the two surfaces.
"""
from __future__ import annotations

from pathlib import Path

import pytest


REPO_ROOT = Path(__file__).resolve().parent.parent
TOPOLOGY = REPO_ROOT / "architecture" / "topology.yaml"
EXPORT = REPO_ROOT / "architecture" / "digest_profiles.py"

# Phase 3 deletion: both the YAML block and the Python mirror are removed in
# ULTIMATE_DESIGN §9.1 Phase 3. Once deleted, these equivalence tests have no
# subject and are skipped rather than errored.
_DIGEST_PROFILES_EXIST = EXPORT.exists()
_skip_if_deleted = pytest.mark.skipif(
    not _DIGEST_PROFILES_EXIST,
    reason="architecture/digest_profiles.py deleted in Phase 3 (ULTIMATE_DESIGN §9.1)",
)


def _load_yaml_profiles() -> list[dict]:
    import yaml
    doc = yaml.safe_load(TOPOLOGY.read_text())
    return doc.get("digest_profiles", []) or []


def _load_python_profiles() -> list[dict]:
    from architecture.digest_profiles import PROFILES
    return PROFILES


@_skip_if_deleted
def test_digest_profiles_count_matches():
    """RELATIONSHIP: same number of profiles in YAML and Python mirror."""
    yaml_profiles = _load_yaml_profiles()
    py_profiles = _load_python_profiles()
    assert len(yaml_profiles) == len(py_profiles), (
        f"profile count drift: yaml={len(yaml_profiles)} python={len(py_profiles)}. "
        f"Run scripts/digest_profiles_export.py to regenerate."
    )


@_skip_if_deleted
def test_digest_profiles_ids_match():
    """RELATIONSHIP: every YAML profile id appears in Python mirror, same order."""
    yaml_ids = [p.get("id") for p in _load_yaml_profiles()]
    py_ids = [p.get("id") for p in _load_python_profiles()]
    assert yaml_ids == py_ids, (
        f"profile id drift: yaml={yaml_ids[:3]}... python={py_ids[:3]}... "
        f"Run scripts/digest_profiles_export.py to regenerate."
    )


@_skip_if_deleted
def test_digest_profiles_byte_for_byte_equivalent():
    """RELATIONSHIP: complete content equivalence between YAML and Python.

    This is the load-bearing antibody. If the YAML edits a single match phrase
    or stop_condition, the .py mirror MUST be regenerated or this test fails.
    Phase 3.5 truth-source flip is safe iff this test stays green for a full
    review cycle.
    """
    yaml_profiles = _load_yaml_profiles()
    py_profiles = _load_python_profiles()
    assert yaml_profiles == py_profiles, (
        "digest_profiles content drift between YAML and Python mirror. "
        "Run scripts/digest_profiles_export.py to regenerate; if you edited "
        "the .py directly, that is forbidden — edit topology.yaml then export."
    )


@_skip_if_deleted
def test_digest_profiles_export_check_passes():
    """RELATIONSHIP: scripts/digest_profiles_export.py --check returns 0.

    Validates the exporter itself can verify in-sync state. If this fails but
    the byte-for-byte test passes, there's an exporter bug (rendering drift).
    """
    import subprocess
    import sys
    result = subprocess.run(
        [sys.executable, str(REPO_ROOT / "scripts" / "digest_profiles_export.py"), "--check"],
        capture_output=True, text=True, check=False, timeout=30,
    )
    assert result.returncode == 0, (
        f"exporter --check failed: stdout={result.stdout!r} stderr={result.stderr!r}"
    )
